apiVersion: v1
kind: Secret
metadata:
  name: molecule-platform-secrets
  namespace: molecule-platform
  labels:
    app.kubernetes.io/name: molecule-platform
    app.kubernetes.io/part-of: molecule-data-platform
    app.kubernetes.io/managed-by: kubectl
    environment: production
    tier: application
    compliance: regulated
  annotations:
    description: "Sensitive configuration data for the Molecular Data Management and CRO Integration Platform"
    security.compliance/21CFR-part-11: "enabled"
    security.compliance/GDPR: "enabled"
    security.compliance/HIPAA: "compliant"
    owner: "platform-team"
    contact: "platform-support@example.com"
type: Opaque
data:
  # Database credentials
  # Contains connection string and authentication details for PostgreSQL database
  DATABASE_URL: cG9zdGdyZXNxbDovL2RiYWRtaW46cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTU0MzIvbW9sZWN1bGVkYg==
  DATABASE_PASSWORD: cGFzc3dvcmQxMjM=
  
  # Application secrets
  # Core security keys for the application
  SECRET_KEY: c2VjcmV0X2tleV9mb3JfYXBwbGljYXRpb25fc2VjdXJpdHk=
  JWT_SECRET: and0X3NlY3JldF9rZXlfZm9yX2F1dGhlbnRpY2F0aW9u
  
  # AWS credentials
  # Authentication for AWS services
  AWS_ACCESS_KEY_ID: QUtJQUlPU0ZPRE5OVkVYQU1QTEU=
  AWS_SECRET_ACCESS_KEY: d0phbHJYVXRuRmVtSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
  
  # AI Engine integration
  # API key for external AI prediction engine
  AI_ENGINE_API_KEY: YWlfZW5naW5lX2FwaV9rZXlfZXhhbXBsZQ==
  
  # DocuSign integration
  # Authentication and configuration for DocuSign e-signature integration
  DOCUSIGN_INTEGRATION_KEY: ZG9jdXNpZ25faW50ZWdyYXRpb25fa2V5X2V4YW1wbGU=
  DOCUSIGN_USER_ID: ZG9jdXNpZ25fdXNlcl9pZF9leGFtcGxl
  DOCUSIGN_ACCOUNT_ID: ZG9jdXNpZ25fYWNjb3VudF9pZF9leGFtcGxl
  DOCUSIGN_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzlGblFLRkUzQlRuWXIKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==
  
  # Email configuration
  # SMTP credentials for sending notifications
  SMTP_USER: c210cF91c2VyX2V4YW1wbGU=
  SMTP_PASSWORD: c210cF9wYXNzd29yZF9leGFtcGxl
  
  # Redis credentials
  # Authentication for Redis cache and message broker
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfZXhhbXBsZQ==
  
  # S3 configuration
  # Storage bucket configuration
  S3_BUCKET_NAME: bW9sZWN1bGUtcGxhdGZvcm0tZGF0YQ==