apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: molecule-platform-backend-hpa
  namespace: molecule-platform
  labels:
    app: backend
    app.kubernetes.io/name: molecule-platform
    app.kubernetes.io/part-of: molecule-data-platform
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
    environment: production
    tier: application
  annotations:
    description: "HorizontalPodAutoscaler for the backend API service of the Molecular Data Management platform"
    owner: "platform-team"
    contact: "platform-support@example.com"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: molecule-platform-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180  # 3 minutes cooldown
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes cooldown
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Max