apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: molecule-platform
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: molecule-data-platform
    app.kubernetes.io/managed-by: kubectl
    tier: database
    compliance: regulated
  annotations:
    backup.velero.io/backup-volumes: "true"
    description: "Persistent storage for PostgreSQL database in the Molecular Data Management platform"
    storage.k8s.io/provisioner-settings: "high-performance"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi