# Dependency review workflow for the Molecular Data Management and CRO Integration Platform
name: Dependency Review

# Trigger this workflow on pull requests to main and develop branches
on:
  pull_request:
    branches: [ main, develop ]

# Set permissions needed for the workflow
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          # Fail on high severity vulnerabilities
          fail-on-severity: high
          # Deny these licenses
          deny-licenses: GPL-3.0, LGPL-2.0
          # Use custom configuration file
          config-file: .github/dependency-review-config.yml